spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    app-topic:
      number-partitions: ${SPRING_KAFKA_APP_TOPIC_NUMBER_PARTITIONS}
      replication-factor: ${SPRING_KAFKA_APP_TOPIC_REPLICATION_FACTOR}
      topic-name: ${SPRING_KAFKA_APP_TOPIC_NAME}
